services:
  edgelake-${EDGELAKE_TYPE}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefiles/edgelake_${EDGELAKE_TYPE}.env
      - .env
    container_name: edgelake-${EDGELAKE_TYPE}
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
      - ${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}
      - 4242:4242/udp
    cap_add:
      - NET_ADMIN  # Adding network administration capabilities for TUN device
    devices:
      - "/dev/net/tun:/dev/net/tun"  # Adding the TUN device to the container
    volumes:
      - edgelake-${EDGELAKE_TYPE}-anylog:/app/EdgeLake/anylog
      - edgelake-${EDGELAKE_TYPE}-blockchain:/app/EdgeLake/blockchain
      - edgelake-${EDGELAKE_TYPE}-data:/app/EdgeLake/data
      - edgelake-${EDGELAKE_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  edgelake-${EDGELAKE_TYPE}-anylog:
  edgelake-${EDGELAKE_TYPE}-blockchain:
  edgelake-${EDGELAKE_TYPE}-data:
  edgelake-${EDGELAKE_TYPE}-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
