services:
  edgelake-${EDGELAKE_TYPE}:
    image: anylogco/edgelake:${TAG}
    restart: always
    env_file:
      - ../docker-makefiles/edgelake_${EDGELAKE_TYPE}.env
    container_name: edgelake-${EDGELAKE_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - edgelake-${EDGELAKE_TYPE}-anylog:/app/EdgeLake/anylog
      - edgelake-${EDGELAKE_TYPE}-blockchain:/app/EdgeLake/blockchain
      - edgelake-${EDGELAKE_TYPE}-data:/app/EdgeLake/data
      - edgelake-${EDGELAKE_TYPE}-local-scripts:/app/deployment-scripts
volumes:
  edgelake-${EDGELAKE_TYPE}-anylog:
  edgelake-${EDGELAKE_TYPE}-blockchain:
  edgelake-${EDGELAKE_TYPE}-data:
  edgelake-${EDGELAKE_TYPE}-local-scripts:
