services:
    remote-cli:
      image: anylogco/remote-cli:latest
      container_name: remote-cli
      restart: always
      stdin_open: true
      tty: true
      ports:
        - 31800:31800
      environment:
        - CONN_IP=0.0.0.0
        - CLI_PORT=31800
      volumes:
        - remote-cli:/app/Remote-CLI/djangoProject/static/json
        - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  edgelake-${EDGELAKE_TYPE}:
    image: anylogco/edgelake:${TAG}
    restart: always
    env_file:
      - docker-makefiles/edgelake_operator_all.env
    container_name: edgelake-${EDGELAKE_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - edgelake-${EDGELAKE_TYPE}-anylog:/app/EdgeLake/anylog
      - edgelake-${EDGELAKE_TYPE}-blockchain:/app/EdgeLake/blockchain
      - edgelake-${EDGELAKE_TYPE}-data:/app/EdgeLake/data
      - edgelake-${EDGELAKE_TYPE}-local-scripts:/app/deployment-scripts
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  edgelake-${EDGELAKE_TYPE}-anylog:
  edgelake-${EDGELAKE_TYPE}-blockchain:
  edgelake-${EDGELAKE_TYPE}-data:
  edgelake-${EDGELAKE_TYPE}-local-scripts:
  remote-cli:
  remote-cli-current:
